### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 4lt3r3go** [DoctorDiffusion/ComfyUI-Doctor-Tools#2]
First of all, thank you for the "last frame selector" node—it’s been very very useful to me. 
Sorry if I’m writing here, but I don’t know how to open a pull request or either contact you. 

I still haven’t found anyone capable of creating an image switcher for nowadays video models, so I’m reaching out to you since it seems like this topic may be more important for you. Maybe you can figure out a way to do this, or perhaps you already know how and are willing to share it.

I’ll try to explain as briefly as possible. 

With all the video models available, some of them have the start and end frame functionality, like COGs. 
The problem is that the existing image switchers don’t allow leaving an empty option.
Let me give you an example: if I want to select an image to be used as "end frame" picked from a series of images, I can use the image switcher.  But if I don’t want any end frame (so give freedom to the model to end as he want) and thus leave the switcher unconnected to an image, the switcher locks up and freeze the workflow from proceeding.

Do you have any idea how to solve this issue? Here’s the post I opened for reference:

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/825

**Comment by DoctorDiffusion** [comment]
I would have separate workflows saved for if I was doing img2vid with or without the start/end point node.

**Comment by 4lt3r3go** [comment]
of course.. it sucks that a simple task like this can't be done.
i guess a month of work on this workflow can be trashed then.
anyway....
![image](https://github.com/user-attachments/assets/1eca790d-abaf-4ce7-ba16-b1dac522e92e)
